services:
    postgres:
        image: postgres:13.3
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
            timeout: 45s
            interval: 10s
            retries: 10
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=engdados
            - APP_DB_USER=docker
            - APP_DB_PASS=docker
            - APP_DB_NAME=docker
        volumes:
            - /tmp/database:/var/lib/postgresql2/data
        ports:
            - 5432:5432

    minio:
        image: minio/minio
        container_name: minio
        environment:
            MINIO_ACCESS_KEY: minioadmin
            MINIO_SECRET_KEY: minio@1234!
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data

    minio_mc:
        image: minio/mc
        container_name: minio_mc
        depends_on:
            - minio
        entrypoint:  |
            sh -c "
            sleep 10 &&
            mc alias set myminio http://minio:9000 minioadmin minio@1234! &&
            mc mb myminio/landing
            "

    postgres-airflow:
        image: postgres:15
        container_name: postgres-airflow
        environment:
            POSTGRES_USER: post_airflow
            POSTGRES_PASSWORD: airflow_123
            POSTGRES_DB: airflow
        ports:
            - 5433:5433
        volumes:
            - postgres_data:/var/lib//postgresql/data

    airflow:
        build:
            context: .
            dockerfile: airflow/config_airflow/airflow.Dockerfile
        container_name: airflow
        environment:
            AIRFLOW_CORE_EXECUTOR: LocalExecutor
            AIRFLOW_CORE_SQL_ALCHEMY_COMN: postgressql+psycopg2://post_airflow:airflow_123@postgres-airflow:5432/airflow
            AIRFLOW_CORE_LOAD_EXAMPLES: 'False'
            AIRFLOW_CORE_DAGS_ARE_PAUSED_AT_CREATION: 'True'
            AIRFLOW_CORE_LOGGING_LEVEL: INFO
            MINIO_ENDPOINT: http://minio:9000
            MINIO_ACCESS_KEY: minioadmin
            MINIO_SECRET_KEY: minio@1234!
        depends_on:
            - postgres-airflow
            - minio
        ports:
            - "8080:8080"
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./airflow/dags:/opt/airflow/config_airflow
            - ./airflow/config_airflow:/opt/airflow/config_airflow
        command: ['airflow', 'standalone']

    metabase:
        image: metabase/metabase:v0.47.1
        container_name: metabase
        environment:
            - MB_DB_TYPE=postgres
            - MB_DB_DBNAME=metabase
            - MB_DB_PORT=5432
            - MB_DB_USER=metabase
            - MB_DB_PASS=metabase_password
            - MB_DB_HOST=postgres-metabase
        ports:
            - "3000:3000"
        depends_on:
            - postgres-metabase
        volumes:
            - metabase_data:/metabase-data

    postgres-metabase:
        image: postgres:15
        container_name: postgres-metabase
        environment:
            POSTGRES_DB: metabase
            POSTGRES_USER: metabase
            POSTGRES_PASSWORD: metabase_password
        ports:
            - "5434:5432"
        volumes:
            - postgres_metabase_data:/var/lib/postgresql/data

volumes:
    postgres_data:
    minio_data:
    metabase_data:
    postgres_metabase_data:
